version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Building the project..."
      - npm install
      - npm run build
artifacts:
  files:
    - "**/*"
