services:
  ec-2-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - ec-2-network

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: ec-2-redis
    networks:
      - ec-2-network

networks:
  ec-2-network:
    driver: bridge
